filebeat.registry_file: /usr/share/filebeat/data/registry

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "docker"
  #pipelines:
  #  - pipeline: "parse_java"
  #    when.contains:
  #      docker.container.name: "java_app"

setup.template.pattern: "docker"
setup.template.name: "docker"

logging.to_files: true

xpack.monitoring:
  enabled: true
  elasticsearch: ~

